def xchat():
    import time
    import turtle
    logo = turtle.Turtle()
    turtle.Screen().bgcolor("black")
    turtle.title("XChat")
    logo.color("red", "yellow")
    logo.begin_fill()
    logo.hideturtle()
    logo.speed(10)
    logo.penup()
    logo.back(200)
    logo.pendown()

    # X
    logo.right(60)
    logo.forward(100)
    logo.left(60)
    logo.forward(20)
    logo.left(120)
    logo.forward(200)
    logo.left(60)
    logo.forward(20)
    logo.left(120)
    logo.forward(100)
    logo.left(120)
    logo.forward(100)
    logo.right(60)
    logo.forward(20)
    logo.right(120)
    logo.forward(200)
    logo.right(60)
    logo.forward(20)
    logo.right(120)
    logo.forward(100)
    logo.end_fill()
    logo.penup()
    logo.back(100)
    logo.pendown()
    # C
    logo.right(60)
    logo.penup()
    logo.forward(180)
    logo.pendown()
    logo.begin_fill()
    logo.circle(50, -180)
    logo.left(90)
    logo.forward(20)
    logo.right(90)
    logo.circle(30, 180)
    logo.right(90)
    logo.forward(20)
    logo.end_fill()

    # H
    logo.left(90)
    logo.penup()
    logo.forward(30)
    logo.left(90)
    logo.pendown()
    logo.begin_fill()
    logo.forward(100)
    logo.right(90)
    logo.forward(20)
    logo.left(90)
    logo.back(40)
    logo.right(90)
    logo.forward(50)
    logo.left(90)
    logo.forward(40)
    logo.right(90)
    logo.forward(20)
    logo.left(90)
    logo.back(100)
    logo.right(90)
    logo.back(20)
    logo.left(90)
    logo.forward(40)
    logo.right(90)
    logo.back(50)
    logo.right(90)
    logo.forward(40)
    logo.left(90)
    logo.back(20)
    logo.end_fill()

    # A
    logo.penup()
    logo.forward(120)
    logo.pendown()
    logo.begin_fill()
    logo.left(60)
    logo.forward(120)
    logo.right(60)
    logo.forward(20)
    logo.right(60)
    logo.forward(120)
    logo.right(120)
    logo.forward(20)
    logo.right(60)
    logo.forward(40)
    logo.left(60)
    logo.forward(40)
    logo.left(60)
    logo.forward(40)
    logo.right(60)
    logo.forward(20)
    logo.end_fill()
    logo.penup()
    logo.right(120)
    logo.forward(55)
    logo.right(60)
    logo.forward(20)
    logo.pendown()
    logo.fillcolor("black")
    logo.begin_fill()
    logo.forward(30)
    logo.left(120)
    logo.forward(30)
    logo.left(120)
    logo.forward(30)
    logo.end_fill()
    logo.penup()
    logo.forward(55)
    logo.pendown()
    logo.fillcolor("yellow")

    # T
    logo.left(120)
    logo.penup()
    logo.forward(150)
    logo.pendown()
    logo.begin_fill()
    logo.forward(20)
    logo.left(90)
    logo.forward(80)
    logo.right(90)
    logo.forward(40)
    logo.left(90)
    logo.forward(20)
    logo.left(90)
    logo.forward(100)
    logo.left(90)
    logo.forward(20)
    logo.left(90)
    logo.forward(40)
    logo.right(90)
    logo.forward(80)
    logo.left(90)
    logo.end_fill()
    time.sleep(3)
    turtle.bye()
    import database
